dist: trusty
sudo: required
cache: yarn
language: node_js
node_js:
  - "7"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_script:
  - sh -e /etc/init.d/xvfb start
  - echo $TRAVIS_BUILD_DIR
#  - cp $TRAVIS_BUILD_DIR/src/environments/environment.ts $TRAVIS_BUILD_DIR/src/environments/environment.prod.ts
install:
  - yarn
script:
# verification de la syntaxe
  - yarn run lint
# compilation du projet
  - yarn run build
# envoi sur le serveur de livraison
  - cd dist
  - tar -zcvf dist-omv-web-desk.tar.gz *
  - curl --header "WAM_UPLOAD_TOKEN: ${WAM_UPLOAD_TOKEN}" --request POST --data-binary "@dist-omv-web-desk.tar.gz"  http://dl.weberantoine.fr/reception.php
